#!/usr/bin/env python3
"""Hermetic E2E acceptance gate for REAL touch drag-select in the agent-
terminal overlay's copy/select mode.

Companion to `agent-term-drag-select-e2e.py` (#342's BUG 2 gate, which only
proves a synthetic Playwright POINTER drag selects text — Playwright's
`page.mouse.*` dispatches real `mousemove` events, but iOS WebKit does NOT
synthesize `mousemove` during a native finger-drag, so that test is a FALSE
POSITIVE for touch: it never exercised the finger-drag path at all).

This script drives REAL `TouchEvent`s (constructed and dispatched in-page via
`page.evaluate`, bypassing Playwright's input pipeline entirely so no
compat-mouse event can leak in) at `.xterm-screen` and asserts:

  1. In COPY MODE, a touch hold-drag selects the exact partial substring
     (not select-all, not empty) via XtermHost.tsx's new touch->mouse
     synthesis bridge, and the floating Copy button copies it to the
     clipboard.
  2. NEGATIVE CONTROL (confound-killer): the SAME touch-drag sequence in
     TYPING mode selects NOTHING (the bridge effect is `copyMode`-gated, so
     it attaches no listeners in typing mode) and the container still pans
     natively (`scrollLeft` moves) — proving the fix is copy-mode-scoped and
     didn't leak into typing mode, and that the assertion above is actually
     produced by the new touch handler rather than some ambient side effect.

Reuses the hermetic "throwaway server.js instance" idiom + tmux fixture +
coordinate-math helpers from agent-term-drag-select-e2e.py; real :4317 is
only ever polled for health, never touched/restarted.

Run (from repo root, after `npm run build` in web/ so web/dist is fresh):
  python3 web/scratch/agent-term-touch-select-e2e.py
"""

import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path
from uuid import uuid4
import json

from playwright.sync_api import sync_playwright

REPO_ROOT = Path(__file__).resolve().parents[2]
SPARE_PORT = 4428  # distinct from agent-term-drag-select-e2e.py's 4427
LIVE_PORT = 4317
SCREENSHOT_DIR = Path.home() / '.claude-control' / 'media' / 'agent-term-touch-select'

TMUX_COLS = 220
TMUX_ROWS = 40
FIXTURE_LINES = 70
MARKER_LINE_INDEX = 60
MARKER_TEXT = 'SELECTME_ABCDEFGHIJKLMNOP_ENDLINE'
SELECT_SUBSTRING = 'ABCDEFGHIJKLMNOP'
PROMPT = 'CCPROMPT$'
PARTIAL_CMD = 'echo CURSOR_PROBE_LEAVE_ME'

# --- JS snippets (identical idiom to agent-term-drag-select-e2e.py) --------

GET_TERM_STATE_JS = """
() => {
  const el = document.querySelector('.agent-term-canvas .term-canvas');
  if (!el) return null;
  const term = el.xtermInstance;
  if (!term) return null;
  return { cols: term.cols, rows: term.rows, fontSize: term.options.fontSize };
}
"""

FIND_MARKER_JS = """
() => {
  const el = document.querySelector('.agent-term-canvas .term-canvas');
  const term = el.xtermInstance;
  const buf = term.buffer.active;
  const marker = 'SELECTME_ABCDEFGHIJKLMNOP_ENDLINE';
  const needle = 'ABCDEFGHIJKLMNOP';
  for (let row = 0; row < term.rows; row++) {
    const line = buf.getLine(buf.viewportY + row);
    if (!line) continue;
    const text = line.translateToString(true);
    if (text.includes(marker)) {
      const startCol = text.indexOf(needle);
      return { row, startCol, endCol: startCol + needle.length, text };
    }
  }
  return null;
}
"""

ROW_GEOMETRY_JS = """
(row) => {
  const el = document.querySelector('.agent-term-canvas .term-canvas');
  const term = el.xtermInstance;
  const screenEl = el.querySelector('.xterm-screen');
  const screenRect = screenEl.getBoundingClientRect();
  const core = term._core;
  const rs = core && core._renderService;
  const cell = rs && rs.dimensions && rs.dimensions.css && rs.dimensions.css.cell;
  const cellWidth = (cell && cell.width) ? cell.width : screenRect.width / term.cols;
  const cellHeight = (cell && cell.height) ? cell.height : screenRect.height / term.rows;
  return {
    screenLeft: screenRect.left,
    rowTop: screenRect.top + row * cellHeight,
    rowHeight: cellHeight,
    cellWidth,
  };
}
"""

GET_SELECTION_JS = """
() => document.querySelector('.agent-term-canvas .term-canvas').xtermInstance.getSelection()
"""

CLEAR_SELECTION_JS = """
() => document.querySelector('.agent-term-canvas .term-canvas').xtermInstance.clearSelection()
"""

# Dispatches a REAL sequence of `TouchEvent`s directly on `.xterm-screen`,
# constructed via the `Touch`/`TouchEvent` constructors (NOT Playwright's
# `page.touchscreen`/CDP input pipeline) -- so no synthetic compat-mouse
# event can be generated by the browser's own input stack. Any selection
# that results is therefore unambiguously produced by XtermHost.tsx's own
# touchstart/touchmove/touchend listeners (the code under test), not by an
# incidental mousemove the browser might otherwise synthesize alongside a
# CDP-driven touch. Steps clientX from startX to endX across N touchmoves,
# holding clientY constant (single-row drag, matching the pointer-drag gate).
TOUCH_DRAG_JS = """
async ({ startX, endX, y, steps, holdMs }) => {
  const el = document.querySelector('.agent-term-canvas .term-canvas');
  const screen = el.querySelector('.xterm-screen');
  const rect = screen.getBoundingClientRect();
  // Touch coordinates must land WITHIN the target element's box for the
  // dispatch to be routed the same way a real finger-contact would be.
  const clampY = Math.min(Math.max(y, rect.top + 1), rect.bottom - 1);
  let identifier = 1;
  const mk = (clientX, clientY) => new Touch({
    identifier, target: screen, clientX, clientY,
    pageX: clientX, pageY: clientY, screenX: clientX, screenY: clientY,
    radiusX: 2, radiusY: 2, rotationAngle: 0, force: 1,
  });
  const fire = (type, touch, changed) => {
    const ev = new TouchEvent(type, {
      bubbles: true, cancelable: true, composed: true,
      touches: type === 'touchend' || type === 'touchcancel' ? [] : [touch],
      targetTouches: type === 'touchend' || type === 'touchcancel' ? [] : [touch],
      changedTouches: [changed],
    });
    screen.dispatchEvent(ev);
  };
  const start = mk(startX, clampY);
  fire('touchstart', start, start);
  await new Promise((r) => setTimeout(r, 16));
  for (let i = 1; i <= steps; i += 1) {
    const x = startX + ((endX - startX) * i) / steps;
    const t = mk(x, clampY);
    fire('touchmove', t, t);
    // Small settle delay per step so this reads as a real drag (not one
    // instantaneous jump) and so mid-drag state is observable for the
    // mid-drag screenshot taken by the caller while still "finger down".
    // eslint-disable-next-line no-await-in-loop
    await new Promise((r) => setTimeout(r, 8));
  }
  if (holdMs) await new Promise((r) => setTimeout(r, holdMs));
  const end = mk(endX, clampY);
  fire('touchend', end, end);
}
"""


def log(msg: str) -> None:
    print(f'[e2e-touch] {msg}', flush=True)


def http_ok(url: str, timeout: float = 2.0) -> bool:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return r.status == 200
    except Exception:
        return False


def wait_for(predicate, timeout_s: float, interval_s: float = 0.3, what: str = 'condition'):
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        if predicate():
            return True
        time.sleep(interval_s)
    raise TimeoutError(f'timed out waiting for: {what}')


def tmux_capture(pane_target: str) -> str:
    r = subprocess.run(
        ['tmux', 'capture-pane', '-p', '-t', pane_target],
        check=True, capture_output=True, text=True,
    )
    return r.stdout


def tmux_last_nonblank_line(pane_target: str) -> str:
    for line in reversed(tmux_capture(pane_target).splitlines()):
        if line.strip():
            return line.rstrip()
    return ''


def select_session(page, tmux_session: str):
    row = page.locator('.session-item[data-kind="claude"]').filter(has_text=tmux_session).first
    row.wait_for(state='visible', timeout=10_000)
    row.click()


def open_overlay(page):
    page.get_by_label('Open agent terminal').click()
    page.locator('.agent-term-panel[role="dialog"]').wait_for(state='visible', timeout=10_000)


def wait_for_convergence(page, cols: int, requested_rows: int, timeout_s: float = 15):
    deadline = time.time() + timeout_s
    last_fs = None
    stable = 0
    last_state = None
    while time.time() < deadline:
        st = page.evaluate(GET_TERM_STATE_JS)
        last_state = st
        if st and st['cols'] == cols and requested_rows - 2 <= st['rows'] <= requested_rows:
            if last_fs is not None and st['fontSize'] == last_fs:
                stable += 1
                if stable >= 3:
                    return st
            else:
                stable = 0
            last_fs = st['fontSize']
        else:
            stable = 0
            last_fs = None
        time.sleep(0.25)
    raise TimeoutError(f'pane-scale convergence did not settle within {timeout_s}s (last={last_state})')


def spawn_hermetic_server(tmp_root: Path):
    fake_home = tmp_root / 'fake-home'
    media_dir = tmp_root / 'media'
    projects_dir = tmp_root / 'projects'
    for d in (fake_home, media_dir / 'apps', projects_dir, tmp_root / 'uploads', tmp_root / 'present'):
        d.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ)
    env.update({
        'HOME': str(fake_home),
        'CLAUDE_CONTROL_PORT': str(SPARE_PORT),
        'CLAUDE_CONTROL_HOST': '127.0.0.1',
        'CLAUDE_CONTROL_PROJECTS': str(projects_dir),
        'CLAUDE_CONTROL_SINGLE_ROOT': '1',
        'CLAUDE_CONTROL_MEDIA': str(media_dir),
        'CLAUDE_CONTROL_UPLOADS': str(tmp_root / 'uploads'),
        'CLAUDE_CONTROL_PRESENT': str(tmp_root / 'present'),
        'CLAUDE_CONTROL_PINS': str(tmp_root / 'pins.json'),
        'CLAUDE_CONTROL_NO_REAP': '1',
    })
    env.pop('CLAUDE_CONTROL_TOKEN', None)
    log(f'spawning hermetic server.js on :{SPARE_PORT}')
    proc = subprocess.Popen(
        ['node', 'server.js'], cwd=str(REPO_ROOT), env=env,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    wait_for(lambda: http_ok(f'http://127.0.0.1:{SPARE_PORT}/api/health'), 15,
             what='hermetic server /api/health 200')
    log('hermetic server is up')
    return proc


def create_tmux_fixture(tmp_root: Path):
    proj_cwd = (tmp_root / 'proj').resolve()
    proj_cwd.mkdir(parents=True, exist_ok=True)
    tmux_session = f'cc-e2e-touch-{uuid4().hex[:8]}'

    subprocess.run(
        ['tmux', 'new-session', '-d', '-s', tmux_session, '-c', str(proj_cwd),
         '-x', str(TMUX_COLS), '-y', str(TMUX_ROWS), 'zsh -f'],
        check=True,
    )
    pane_target = subprocess.run(
        ['tmux', 'list-panes', '-t', tmux_session, '-F', '#{session_name}:#{window_index}.#{pane_index}'],
        check=True, capture_output=True, text=True,
    ).stdout.strip().splitlines()[0]
    subprocess.run(['tmux', 'set-option', '-p', '-t', pane_target, '@cc_agent', 'claude'], check=True)
    subprocess.run(['tmux', 'rename-window', '-t', tmux_session, tmux_session], check=True)
    log(f'created tmux session {tmux_session} (pane {pane_target}) at cwd={proj_cwd}')

    subprocess.run(['tmux', 'send-keys', '-t', pane_target, f"export PS1='{PROMPT} '", 'Enter'], check=True)
    wait_for(lambda: tmux_last_nonblank_line(pane_target) == PROMPT, 8, what='PS1 applied')

    lines = []
    for i in range(FIXTURE_LINES):
        lines.append(MARKER_TEXT if i == MARKER_LINE_INDEX else f'filler-row-{i:03d}-' + ('x' * 20))
    fixture_path = tmp_root / 'fixture.txt'
    fixture_path.write_text('\n'.join(lines) + '\n')

    subprocess.run(['tmux', 'send-keys', '-t', pane_target, f'cat {fixture_path}', 'Enter'], check=True)
    wait_for(lambda: tmux_last_nonblank_line(pane_target) == PROMPT, 8, what='cat finished, fresh prompt returned')

    subprocess.run(['tmux', 'send-keys', '-t', pane_target, '-l', PARTIAL_CMD], check=True)
    wait_for(lambda: tmux_last_nonblank_line(pane_target) == f'{PROMPT} {PARTIAL_CMD}', 8,
             what='partial command rendered at prompt')

    log('tmux fixture ready: cat output visible + partial command at cursor row')
    return tmux_session, pane_target


def dispatch_touch_drag(page, start_x, end_x, y, steps=10, hold_ms=120):
    page.evaluate(TOUCH_DRAG_JS, {'startX': start_x, 'endX': end_x, 'y': y, 'steps': steps, 'holdMs': hold_ms})


def cdp_touch_drag(cdp, start_x, end_x, y, steps=12, hold_ms=0):
    """Drive a REAL touch drag through Chromium's own input pipeline via CDP
    `Input.dispatchTouchEvent` -- unlike `dispatch_touch_drag` (a page-side
    `TouchEvent` constructed and `dispatchEvent()`'d in JS, which only ever
    reaches JS listeners and never feeds the browser's native touch-scroll
    compositor path), this goes through the SAME pipeline a physical finger
    would: Chromium's compositor decides whether to pan based on the live
    `touch-action` of whatever the touch lands on, exactly like a real
    device. Used ONLY for the typing-mode negative control's "does it still
    pan" assertion -- `overflow-x:auto` native scrolling cannot be proven any
    other way from Playwright. NOT used for the copy-mode selection
    assertion (kept on the page-side JS dispatch instead, since that path is
    provably immune to the browser's touchstart-not-prevented compat-mouse
    synthesis and so is the more airtight proof the SELECTION specifically
    came from XtermHost.tsx's own touch->mouse bridge, not an incidental
    compat event)."""
    cdp.send('Input.dispatchTouchEvent', {'type': 'touchStart', 'touchPoints': [{'x': start_x, 'y': y, 'id': 1}]})
    for i in range(1, steps + 1):
        x = start_x + (end_x - start_x) * i / steps
        cdp.send('Input.dispatchTouchEvent', {'type': 'touchMove', 'touchPoints': [{'x': x, 'y': y, 'id': 1}]})
        time.sleep(0.01)
    if hold_ms:
        time.sleep(hold_ms / 1000)
    cdp.send('Input.dispatchTouchEvent', {'type': 'touchEnd', 'touchPoints': []})


def run_touch_select(base_url: str, tmux_session: str) -> dict:
    with sync_playwright() as p:
        browser = p.chromium.launch()
        # has_touch=True is what makes Chromium report `ontouchstart` support
        # and route Touch/TouchEvent dispatch through its real touch input
        # path instead of silently no-op'ing it.
        context = browser.new_context(
            has_touch=True,
            viewport={'width': 1400, 'height': 960},
            reduced_motion='reduce',
        )
        context.grant_permissions(['clipboard-read', 'clipboard-write'], origin=base_url)
        page = context.new_page()
        cdp = context.new_cdp_session(page)
        page.goto(base_url)

        select_session(page, tmux_session)
        open_overlay(page)
        state = wait_for_convergence(page, TMUX_COLS, TMUX_ROWS)
        log(f'pane-scale converged: {state}')

        # --- enter copy/select mode ---
        page.locator('.modal-copytoggle').click()
        page.wait_for_selector('.modal-copytoggle[aria-pressed="true"]', timeout=5_000)

        found = page.evaluate(FIND_MARKER_JS)
        assert found, 'SELECTME marker row not found on screen (fixture/scroll assumption broke)'
        geo = page.evaluate(ROW_GEOMETRY_JS, found['row'])
        cell_w = geo['cellWidth']
        start_x = geo['screenLeft'] + found['startCol'] * cell_w + 1
        end_x = geo['screenLeft'] + found['endCol'] * cell_w - 1
        row_y = geo['rowTop'] + geo['rowHeight'] / 2

        page.evaluate(CLEAR_SELECTION_JS)

        # --- COPY MODE: real TouchEvent hold-drag ---
        SCREENSHOT_DIR.mkdir(parents=True, exist_ok=True)
        # Fire everything up to (not including) touchend, screenshot while the
        # "finger" is still down, then finish the gesture -- mirrors the
        # pointer gate's mid-drag screenshot semantics using a manual two-part
        # dispatch instead of TOUCH_DRAG_JS's single awaited call.
        page.evaluate(
            """
            ({ startX, endX, y }) => {
              window.__touchDragState = { startX, endX, y };
              const el = document.querySelector('.agent-term-canvas .term-canvas');
              const screen = el.querySelector('.xterm-screen');
              const rect = screen.getBoundingClientRect();
              const clampY = Math.min(Math.max(y, rect.top + 1), rect.bottom - 1);
              const mk = (clientX, clientY) => new Touch({
                identifier: 1, target: screen, clientX, clientY,
                pageX: clientX, pageY: clientY, screenX: clientX, screenY: clientY,
                radiusX: 2, radiusY: 2, rotationAngle: 0, force: 1,
              });
              const fire = (type, touch) => screen.dispatchEvent(new TouchEvent(type, {
                bubbles: true, cancelable: true, composed: true,
                touches: [touch], targetTouches: [touch], changedTouches: [touch],
              }));
              const start = mk(startX, clampY);
              fire('touchstart', start);
              const mid = mk((startX + endX) / 2, clampY);
              fire('touchmove', mid);
              const end = mk(endX, clampY);
              fire('touchmove', end);
              window.__touchDragEnd = end;
              window.__touchDragScreen = screen;
            }
            """,
            {'startX': start_x, 'endX': end_x, 'y': row_y},
        )
        page.wait_for_timeout(80)
        page.screenshot(path=str(SCREENSHOT_DIR / 'mid-drag-selection.png'))  # finger still "down"

        selection_mid_drag = page.evaluate(GET_SELECTION_JS)
        log(f'mid-drag (before touchend) selection: {selection_mid_drag!r}')

        page.evaluate(
            """
            () => {
              const screen = window.__touchDragScreen;
              const end = window.__touchDragEnd;
              screen.dispatchEvent(new TouchEvent('touchend', {
                bubbles: true, cancelable: true, composed: true,
                touches: [], targetTouches: [], changedTouches: [end],
              }));
            }
            """
        )
        page.wait_for_timeout(50)

        selection = page.evaluate(GET_SELECTION_JS)
        assert selection == SELECT_SUBSTRING, (
            f'TOUCH drag-select: expected exact partial substring {SELECT_SUBSTRING!r} via real TouchEvents, '
            f'got {selection!r} (mid-drag was {selection_mid_drag!r}) -- either the touch->mouse synthesis '
            'bridge did not attach, or the selection was claimed as a pan/gesture instead'
        )
        log(f'REAL TOUCH drag-select produced exact partial substring: {selection!r}')

        copy_btn = page.get_by_role('button', name='Copy', exact=True)
        copy_btn.wait_for(state='visible', timeout=5_000)
        copy_btn.click()
        page.wait_for_timeout(150)
        clipboard = page.evaluate('async () => await navigator.clipboard.readText()')
        assert clipboard == SELECT_SUBSTRING, f'TOUCH: clipboard mismatch, expected {SELECT_SUBSTRING!r} got {clipboard!r}'
        log(f'Copy button copied exact substring (from touch-produced selection): {clipboard!r}')
        page.screenshot(path=str(SCREENSHOT_DIR / 'after-copy.png'))

        # --- NEGATIVE CONTROL: exit copy mode, SAME touch-drag must select
        # NOTHING (bridge is copyMode-gated -> no listeners attached) and the
        # container must still pan (native overflow-x:auto touch-scroll). ---
        page.evaluate(CLEAR_SELECTION_JS)
        page.locator('.modal-copytoggle').click()
        page.wait_for_selector('.modal-copytoggle[aria-pressed="false"]', timeout=5_000)

        canvas = page.locator('.agent-term-canvas .term-canvas')
        overflow_x = canvas.evaluate("(el) => getComputedStyle(el).overflowX")
        touch_action = canvas.evaluate("(el) => getComputedStyle(el).touchAction")
        assert overflow_x == 'auto', f'typing-mode overflow-x should be auto, got {overflow_x!r}'
        assert touch_action != 'none', f'typing-mode touch-action should allow panning, got {touch_action!r}'

        # Re-find the marker row/coords -- exiting copy mode may have shifted
        # scroll position back, and geometry can differ slightly (padding
        # changes are NOT expected, but re-measuring is cheap and correct).
        found2 = page.evaluate(FIND_MARKER_JS)
        geo2 = page.evaluate(ROW_GEOMETRY_JS, found2['row']) if found2 else geo
        cell_w2 = geo2['cellWidth']
        start_x2 = geo2['screenLeft'] + (found2['startCol'] if found2 else found['startCol']) * cell_w2 + 1
        end_x2 = geo2['screenLeft'] + (found2['endCol'] if found2 else found['endCol']) * cell_w2 - 1
        row_y2 = geo2['rowTop'] + geo2['rowHeight'] / 2

        dispatch_touch_drag(page, start_x2, end_x2, row_y2, steps=10, hold_ms=80)
        page.wait_for_timeout(100)

        typing_mode_selection = page.evaluate(GET_SELECTION_JS)
        assert not typing_mode_selection, (
            f'NEGATIVE CONTROL FAILED: typing-mode touch-drag produced a selection ({typing_mode_selection!r}) -- '
            'the touch->mouse bridge (or a browser compat-mouse event) leaked into typing mode'
        )
        log(f'typing-mode negative control: touch-drag selected nothing (selection={typing_mode_selection!r}) -- OK')

        scroll_before = canvas.evaluate('(el) => el.scrollLeft')
        # A real touch-driven pan gesture, via CDP (see cdp_touch_drag's doc
        # comment: page-side `dispatchEvent(new TouchEvent(...))` never
        # reaches Chromium's native touch-scroll compositor path, only JS
        # listeners -- proving native `overflow-x:auto` pan survives requires
        # driving the browser's REAL input pipeline). Swipe leftward (finger
        # moves right to left), which scrolls content rightward, i.e.
        # increases scrollLeft.
        box = canvas.bounding_box()
        pan_y = box['y'] + box['height'] / 2
        pan_start_x = box['x'] + box['width'] * 0.75
        pan_end_x = box['x'] + box['width'] * 0.25
        cdp_touch_drag(cdp, pan_start_x, pan_end_x, pan_y, steps=12, hold_ms=0)
        page.wait_for_timeout(200)
        scroll_after = canvas.evaluate('(el) => el.scrollLeft')
        assert scroll_after != scroll_before, (
            f'NEGATIVE CONTROL FAILED: typing-mode touch-drag should still pan, scrollLeft stayed at {scroll_before}'
        )
        log(f'typing-mode touch-drag still pans (via CDP native input): scrollLeft {scroll_before} -> {scroll_after}')

        browser.close()
        return {
            'selection': selection,
            'clipboard': clipboard,
            'typing_mode_selection': typing_mode_selection,
            'scroll_before': scroll_before,
            'scroll_after': scroll_after,
        }


def main() -> int:
    assert http_ok(f'http://127.0.0.1:{LIVE_PORT}/'), 'live :4317 must be up (200) before the test starts'
    log(f'baseline: live :{LIVE_PORT} is 200')

    tmp_root = Path(tempfile.mkdtemp(prefix='agent-term-touch-select-e2e-')).resolve()
    server_proc = None
    tmux_session = None

    try:
        server_proc = spawn_hermetic_server(tmp_root)
        tmux_session, pane_target = create_tmux_fixture(tmp_root)
        base_url = f'http://127.0.0.1:{SPARE_PORT}'

        def session_visible():
            try:
                with urllib.request.urlopen(f'http://127.0.0.1:{SPARE_PORT}/api/sessions', timeout=2) as r:
                    data = json.loads(r.read())
                    sessions = data.get('sessions', data) if isinstance(data, dict) else data
                    return any(s.get('target') == pane_target for s in sessions)
            except Exception:
                return False

        wait_for(session_visible, 20, what='synthetic session bound + visible via /api/sessions')
        log('synthetic session is bound and visible')

        result = run_touch_select(base_url, tmux_session)

        screenshots = [
            SCREENSHOT_DIR / 'mid-drag-selection.png',
            SCREENSHOT_DIR / 'after-copy.png',
        ]
        for shot in screenshots:
            assert shot.exists() and shot.stat().st_size > 0, f'screenshot not written: {shot}'
        log('screenshots confirmed on disk: ' + ', '.join(str(s) for s in screenshots))

        log(
            f"TOUCH PASS: dragged/copied substring={result['selection']!r}, "
            f"typing-mode touch selection={result['typing_mode_selection']!r} (expected empty), "
            f"typing-mode scrollLeft {result['scroll_before']} -> {result['scroll_after']}"
        )

        assert http_ok(f'http://127.0.0.1:{LIVE_PORT}/'), 'live :4317 must still be 200 after the test'
        log(f'live :{LIVE_PORT} still 200 after the test')

        log('PASS')
        return 0

    finally:
        log('tearing down')
        if tmux_session:
            subprocess.run(['tmux', 'kill-session', '-t', tmux_session], check=False, stderr=subprocess.DEVNULL)
        if server_proc is not None:
            server_proc.terminate()
            try:
                server_proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                server_proc.kill()
                server_proc.wait(timeout=5)
        shutil.rmtree(tmp_root, ignore_errors=True)
        log('teardown complete (spawned server killed, tmux session killed, tmp dirs removed)')


if __name__ == '__main__':
    sys.exit(main())
